### ISSUE TITLE
Problem with cyrillic symbols

### ISSUE THREAD

**Issue by F1nansist** [FF-Projects-UE/UE_LibHaru#2]
Hi, @ffreality 

Plugin works great until u dont try to add cyrillic symbols to pdf. As i know to whole problem is in UTF-8 (i tried ISO-8859-5, CP1251).
I had parsing problem with cyrillic in Unreal Engine and then utf 16 resolved my problem. Maybe it can help u somehow.

**Comment by ffreality** [comment]
Thanks and let me check it but I think I saw a cyrillic related issue on LibHaru.
Sometimes this kind of problems are related with library itself and LibHaru doesn't have a good maintenance

**Comment by ffreality** [comment]
Okay found your problem. It is not about UTF-16 infact if I use `HPDF_SetCurrentEncoder(PDF_Document, "UTF-16");` program crash.
You probably used `Standart Fonts`. They don't support extended characters. For example, I am Turkish and my surname contains `Ö` character. Standart fonts can't write it.

Adding cyrillic support to standart fonts is not our or even LibHaru's job. Because LibHaru use what PDF standart gives them and we use what LibHaru has. For this reason, you need to use an external font. You can see a node for that.

and you can download an external font from here
https://www.1001fonts.com/cyrillic-fonts.html

I used first one and result is like this.
[sample_libharu.pdf](https://github.com/FF-Projects-UE/UE_LibHaru/files/12092097/sample_libharu.pdf)

**Comment by F1nansist** [comment]
Yeah, it works perfectly. Thank you
