### ISSUE TITLE
Export path

### ISSUE THREAD

**Issue by F1nansist** [FF-Projects-UE/UE_LibHaru#3]
Hi again!

In method "LibHaru_Save_File" Export_Path is validating if this var is not empty but path can be not valid like there is no folder in this path. This method returns true as PDF was created but if folder doesnt exist pdf will not be created.

There is a way to validate path throw UE btw, but i think it will be great to add path validation into method "LibHaru_Save_File"

**Comment by ffreality** [comment]
I can expose HPDF_STATUS to show if PDF created or not with its details.
But I don't think just checking directory with UE in function is a good solution.
Because users can expect automatic actions from plugin.
These kinds of validations should be done from users.

**Comment by F1nansist** [comment]
Bool return value is not fair in this case. It return True even PDF is not created because of invalid path

**Comment by ffreality** [comment]
No, I am agree with you about return value. I will change it. I say I just won't use unreal's api to check folders.
Return value will be bool + string error code based on HPDF_RESULT.
If path is not avaible, it will return false + "4119 or 1017"

I will look at how can I give a more meaningful outcode than integer based codes.

And I said users should check their path, because they will decide what will be next step if there is a path problem ?
if they detect any problem, they can create that path, they can save pdf to a default path or they can throw an error.

**Comment by F1nansist** [comment]
I agree with you in this case but in my case i should create path by myself so i will use unreal for this purpose. Thank you for fast answer

**Comment by ffreality** [comment]
okay done and pushed.

If there is an error (not just paths but anything), it won't return true and there is an `OutCode` string output to say you what's going on.

OutCode is a hexademical value and you can check them from here.
https://github.com/libharu/libharu/wiki/Error-handling

but as I say before, it will be wise to do validations by yourself. Because it will just give you false and error code but not take any action to continue operation.
