### ISSUE TITLE
Problem add text

### ISSUE THREAD

**Issue by kostyazhy** [FF-Projects-UE/UE_LibHaru#6]
Hello!
My appeared in the LibHaru_Add_Text method in the Array_Pages.Add(First_Page) line;
Array_Pages = extracting data from value failed. 
<img width="580" alt="Error extracting data from value failed" src="https://github.com/FF-Plugins-Docs/FF_LibHaru/assets/8112195/1aa7f60b-839d-4484-9161-cf9f3390fbe4">.
Please help me!

**Comment by ffreality** [comment]
1- Show me your blueprints.
2- Make sure that your engine is 5.2
3- Send me the text which you want to add.

**Comment by kostyazhy** [comment]
Thank you!
I use engine 5.1. Now update engine. 
My text = Hello word.
My blueprint https://blueprintue.com/blueprint/jcdvk6qo/

**Comment by ffreality** [comment]
I tried it and it works.
1- Install 5.2
2- Create a C++ project
3- Generate Visual Studio Project Files from .uproject
4- Build plugin
5- Use.

There is a sample blueprint template and widget in plugin's content folder. Open UI_LibHaru and break `Add U3D Model` node's connection. If you have .u3d model, you can try it as well.
Also edit paths based on your locations.

When you start your game, you will see a text box to write something to pdf file.

**Comment by kostyazhy** [comment]
I updated the engine version to 5.2. But the error was repeated. You can explain the  - "4-Build plugin". I used this instruction:
1.Create a "Plugins" folder in the C++ project's root folder.
2.Copy the plugin(s) folder(s) you want to build into the newly created "Plugins" folder.
3.Manually delete the “Intermediate” and “Binaries” folders of the plugin(s).
4.Double-click on your .uproject file to relaunch the Editor. You should see a popup telling you that some modules need to be rebuilt.   Click Accept.  This should rebuild your plugin(s).
 What exactly needs to be done?

**Comment by ffreality** [comment]
I wrote to ReadMe that you need to install ExtendedVars plugin as well.
https://github.com/FF-Plugins-Misc/ExtendedVars

right click your .uproject, you will see "Generate Projects Files" button.
Press that. When you finish it, open your .sln file and press F5

**Comment by kostyazhy** [comment]
I checked ExtendedVars and your FF_Library plugin is located in the plugins folder. In the Editor, I checked that there are ticks in the plugins window opposite the plugin names

**Comment by ffreality** [comment]
Look man, I opened a new project, download it and started to use it. There is no problem. If you have a problem on your engine or visual studio installation, it's not my problem.

Let me give a teamviewer and allow me to connect your computer.
If there is a problem on my side, I say I am sorry and will fix it.
But if you got a problem I will make my plugin private.

**Comment by kostyazhy** [comment]
I'm sorry if I offended you. Thank you for your hard work and for your help.

**Comment by ffreality** [comment]
Just look at your error codes.
bAllowChop is a boolean and your IDE says it is not valid. a boolean ? valid ?
and literally every variable has green underline.

This means, you couldn't install plugin correctly and Unreal Engine couldn't compile it.
It looks like you use Rider. I don't use Rider but I don't think problem is your IDE.

If you want to install a new plugin (not only mine but every other github plugin)
- Make sure that you installed correct engine and dependencies
- Copy plugin to Plugins folder
- Delete binaries, intermediate and saved folder
- Generate Visual Studio Project Files
- Open Visual Studio
- Press F5

Your problem starts from "Generate Visual Studio Project Files" section. Your Rider can't add it to UnrealBuildTool list. You need to somehow refresh it.

And I am offending because my plugin literally has no specific configuration and I can use it. (look at the pdf at bellow)
But I need to solve people's different installation problems :D

Someone opened an issue because he used a font which can't support cyrillic characters :D
So, I am really okay to give you personal assistance on Teamviewer but if this is your problem, it makes me done :D

[sample_libharu.pdf](https://github.com/FF-Plugins-Docs/FF_LibHaru/files/12620805/sample_libharu.pdf)
